FROM cerit.io/os/ubuntu:22.04-user

# Cryosparc
ARG LICENSE=74f2d264-77d7-11ed-bb40-63f6990bba5f
RUN apt-get update && fakeroot apt-get -y --no-install-recommends install nvidia-cuda-toolkit libcudart11.0:amd64 curl python3 python3-pip  libtiff5 python3-setuptools python3-dev zip unzip openssh-server && apt-get clean && rm -rf /var/lib/apt/lists/*  && ln -s /bin/true /usr/bin/ping && sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config &&  sed -i 's/.*ClientAliveInterval.*/ClientAliveInterval 30/g' /etc/ssh/sshd_config &&  sed -i 's/#Port 22.*/Port 2222/g' /etc/ssh/sshd_config &&  sed -i 's/UsePAM.*/UsePAM no/g' /etc/ssh/sshd_config && echo "PubkeyAcceptedKeyTypes=+ssh-rsa" >> /etc/ssh/sshd_config 
RUN fakeroot addgroup --gid 1000 cryo &&  fakeroot adduser --gid 1000 --uid 1000 --disabled-password --gecos cryo cryo
RUN cd /opt && mkdir /opt/cryosparc_database && curl -L https://get.cryosparc.com/download/worker-latest/$LICENSE | tar xzvf -  && \
    cd cryosparc_worker && ./install.sh --license $LICENSE --yes 

WORKDIR /opt/cryosparc_worker
