# Image of cryosparc master and worker (Optimized for speed of build not for size)

FROM cerit.io/os/ubuntu:22.04-user

# Cryosparc
ARG LICENSE_ID=74f2d264-77d7-11ed-bb40-63f6990bba5f
#ARG CRYOSPARC_PATH=/opt/cryosparc_master

RUN apt-get update && fakeroot apt-get -y --no-install-recommends install \
    curl \
    python3 \
    python3-pip \
     libtiff5 \
     python3-setuptools \
     python3-dev \
     zip \
     unzip \
     openssh-server \
     vim \
     fish && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*  && \
    ln -s /bin/true /usr/bin/ping && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config &&  \
    sed -i 's/.*ClientAliveInterval.*/ClientAliveInterval 30/g' /etc/ssh/sshd_config && \
    sed -i 's/#Port 22.*/Port 2222/g' /etc/ssh/sshd_config && \
    sed -i 's/UsePAM.*/UsePAM no/g' /etc/ssh/sshd_config && \
    echo "PubkeyAcceptedKeyTypes=+ssh-rsa" >> /etc/ssh/sshd_config

RUN fakeroot addgroup --gid 1000 cryo &&  fakeroot adduser --gid 1000 --uid 1000 --disabled-password --gecos cryo cryo

# Install worker
RUN curl -L https://get.cryosparc.com/download/worker-latest/$LICENSE_ID -o /opt/cryosparc_worker.tar.gz && \
    tar xzvf /opt/cryosparc_worker.tar.gz -C /opt/ && \
    rm /opt/cryosparc_worker.tar.gz


RUN cd /opt/cryosparc_worker && \
    ./install.sh    \
                    --license $LICENSE_ID \
                    --yes

RUN fakeroot chown -R 1000:1000 /opt/cryosparc_worker/

# Install jobs_cmd
COPY --chown=1000:1000 requirements.txt /tmp/jobs_cmd/requirements.txt
RUN pip3 install -r /tmp/jobs_cmd/requirements.txt
COPY --chown=1000:1000 src /usr/local/bin

#CMD ["/usr/bin/fish"]
