# Image of cryosparc master only

FROM cerit.io/os/ubuntu:22.04-user

# Cryosparc
ARG LICENSE_ID=74f2d264-77d7-11ed-bb40-63f6990bba5f
ARG CRYOSPARC_PATH=/opt/cryosparc_master

RUN apt-get update && fakeroot apt-get -y --no-install-recommends install \
    curl \
    python3 \
    python3-pip \
     libtiff5 \
     python3-setuptools \
     python3-dev \
     zip \
     unzip \
     openssh-server \
     vim \
     fish && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*  && \
    ln -s /bin/true /usr/bin/ping && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config &&  \
    sed -i 's/.*ClientAliveInterval.*/ClientAliveInterval 30/g' /etc/ssh/sshd_config && \
    sed -i 's/#Port 22.*/Port 2222/g' /etc/ssh/sshd_config && \
    sed -i 's/UsePAM.*/UsePAM no/g' /etc/ssh/sshd_config && \
    echo "PubkeyAcceptedKeyTypes=+ssh-rsa" >> /etc/ssh/sshd_config

RUN fakeroot addgroup --gid 1000 cryo &&  fakeroot adduser --gid 1000 --uid 1000 --disabled-password --gecos cryo cryo

# Install master
RUN curl -L https://get.cryosparc.com/download/master-latest/$LICENSE_ID -o $CRYOSPARC_PATH.tar.gz && \
    tar xzvf $CRYOSPARC_PATH.tar.gz -C /opt/ && \
    rm $CRYOSPARC_PATH.tar.gz

#RUN cd $CRYOSPARC_PATH && ./install.sh --license $LICENSE_ID --yes --dbpath /opt/cryosparc_database --port 8080 --hostname 127.0.0.1

RUN mkdir /opt/cryosparc_database && \
    cd $CRYOSPARC_PATH && \
    ./install.sh    \
                    --license $LICENSE_ID \
                    --hostname 127.0.0.1 \
                    --port 8080 \
                    --dbpath /opt/cryosparc_database \
                    --yes

RUN sed -i 's:    disk_has_space=.*:    disk_has_space="true":g'  $CRYOSPARC_PATH/bin/cryosparcm
RUN echo "CRYOSPARC_FORCE_HOSTNAME=true" >>  $CRYOSPARC_PATH/config.sh && echo "CRYOSPARC_HOSTNAME_CHECK=false" >> $CRYOSPARC_PATH/config.sh
RUN fakeroot chown -R 1000:1000 $CRYOSPARC_PATH/

# Install jobs_cmd
COPY --chown=1000:1000 requirements.txt /tmp/jobs_cmd/requirements.txt
RUN pip3 install -r /tmp/jobs_cmd/requirements.txt
COPY --chown=1000:1000 src /usr/local/bin
# to bin/ because cluster_config.json need to be in path for cryosparcw to find it
COPY --chown=1000:1000 entrypoints $CRYOSPARC_PATH

WORKDIR $CRYOSPARC_PATH
