kind: Pod
apiVersion: v1
metadata:
  name: cryosparc-master
spec:
  containers:
    - name: cryosparc-master
      image: cerit.io/cerit/cryosparc:master-v0.2
      imagePullPolicy: Always
      command: [ "/bin/bash", "-c" ]
      args: [ "while :; do sleep 10000; done" ]
      #          env:
      #            - name: COMPOSE_HTTP_TIMEOUT
      #              value: "480"
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "4Gi"
          cpu: "2"
        limits:
          memory: "4Gi"
          cpu: "2"
#          nvidia.com/gpu: "1" # NOTE: Not neccecary here
#          nvidia.com/mig-1g.10gb: "1" # NOTE: Not neccecary here
      securityContext: # Container security context
#        privileged: true
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - name: vol-1
          mountPath: /mnt
  volumes:
    - name: vol-1
      persistentVolumeClaim:
        claimName: pvc-cryosparc-scratch
