kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-cryosparc-scratch
#  annotations:
#    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: "nfs-csi"
