kind: Service
apiVersion: v1
metadata:
  name: cryosparc-svc

  labels:
    name: cryosparc-svc
spec:
  type: ClusterIP
  selector:
    app: cryosparc
  # Connecting ports for cryosparc application (8080) and cryosparc web (80)
  ports:
    - name: cryosparc-port
      protocol: TCP
      targetPort: 8080
      port: 80