## Create a Role that allows creating jobs in the "batch" API group within the "default" namespace.
#apiVersion: rbac.authorization.k8s.io/v1
#kind: Role
#metadata:
#  name: cryosparc-role
#  namespace: zdeneklapeseinfracesnetcz-ns
#rules:
#  - apiGroups: [ "batch" ]
#    resources: [ "jobs", "jobs/status" ]
#    verbs: [ "create", "get", "delete" ]
